### ISSUE TITLE
error in VAE.py

### ISSUE THREAD

**Issue by eyaler** [google/compare_gan#15]
Traceback (most recent call last):
  File "compare_gan_run_one_task", line 71, in <module>
    tf.app.run()
  File "C:\anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "compare_gan_run_one_task", line 57, in main
    gan_lib.run_with_options(options, task_workdir)
  File "c:\users\e\python\compare_gan\compare_gan\src\gan_lib.py", line 255, in run_with_options
    gan.train(sess, progress_reporter)
  File "c:\users\e\python\compare_gan\compare_gan\src\gans\abstract_gan.py", line 441, in train
    d_loss, g_loss = self.run_single_train_step(features, step, g_loss, sess)
TypeError: run_single_train_step() missing 1 required positional argument: 'sess'

**Comment by eyaler** [comment]
fixed by changing:

``` 
 def run_single_train_step(self, batch_images, batch_z, counter, g_loss, sess):
```
to

```
  def run_single_train_step(self, features, counter, g_loss, sess):
    batch_images = features['images']
    batch_z = features['z_for_gen_step']
```

**Comment by Marvin182** [comment]
We just released an update of the library and VAEs are no longer part of it. You can continue to use the v2 branch and if you send a pull request to fix this I will merge it.
