### ISSUE TITLE
division by zero error in task 8

### ISSUE THREAD

**Issue by eyaler** [google/compare_gan#16]
Traceback (most recent call last):
  File "compare_gan_run_one_task", line 71, in <module>
    tf.app.run()
  File "C:\anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "compare_gan_run_one_task", line 65, in main
    "inceptionv1_for_inception_score.pb")))
  File "c:\users\e\python\compare_gan\compare_gan\src\eval_gan_lib.py", line 888, in RunTaskEval
    tasks_to_run)
  File "c:\users\e\python\compare_gan\compare_gan\src\eval_gan_lib.py", line 778, in RunCheckpointEval
    result_dict.update(task.RunInSession(options, sess, gan, real_images))
  File "c:\users\e\python\compare_gan\compare_gan\src\eval_gan_lib.py", line 524, in RunInSession
    return ComputeAccuracyLoss(options, sess, gan, real_images)
  File "c:\users\e\python\compare_gan\compare_gan\src\eval_gan_lib.py", line 310, in ComputeAccuracyLoss
    train_accuracy = sum(train_predictions) / float(len(train_predictions))
ZeroDivisionError: float division by zero

**Comment by Marvin182** [comment]
Not sure what is happening there. Closing this because the code does not exists in the new version. Please try the new version.
