### ISSUE TITLE
 module 'tensorflow' has no attribute 'GraphKeys'

### ISSUE THREAD

**Issue by Sajal-1** [google/compare_gan#47]
Getting this error despite doing __pip install -e .__

__$ python main.py --help
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    from compare_gan import runner_lib
  File "/home/maths/dual/mt6160653/biggan/compare_gan-master/compare_gan/runner_lib.py", line 30, in <module>
    from compare_gan import eval_gan_lib
  File "/home/maths/dual/mt6160653/biggan/compare_gan-master/compare_gan/eval_gan_lib.py", line 27, in <module>
    from compare_gan import eval_utils
  File "/home/maths/dual/mt6160653/biggan/compare_gan-master/compare_gan/eval_utils.py", line 35, in <module>
    import tensorflow_gan as tfgan
  File "/home/maths/dual/mt6160653/.local/lib/python3.6/site-packages/tensorflow_gan/__init__.py", line 72, in <module>
    from tensorflow_gan.python import *  # pylint: disable=wildcard-import
  File "/home/maths/dual/mt6160653/.local/lib/python3.6/site-packages/tensorflow_gan/python/__init__.py", line 36, in <module>
    from tensorflow_gan.python import estimator
  File "/home/maths/dual/mt6160653/.local/lib/python3.6/site-packages/tensorflow_gan/python/estimator/__init__.py", line 24, in <module>
    from .gan_estimator import *
  File "/home/maths/dual/mt6160653/.local/lib/python3.6/site-packages/tensorflow_gan/python/estimator/gan_estimator.py", line 28, in <module>
    from tensorflow_gan.python import contrib_utils as contrib
  File "/home/maths/dual/mt6160653/.local/lib/python3.6/site-packages/tensorflow_gan/python/contrib_utils.py", line 48, in <module>
    collection=tf.GraphKeys.GLOBAL_VARIABLES):
AttributeError: module 'tensorflow' has no attribute 'GraphKeys'__

I have read [this](https://stackoverflow.com/questions/59890090/tensorflow-2-1-0-error-module-tensorflow-has-no-attribute-graphkeys) but I cannot alter the package __tensorflow_gan__.

**Comment by Sajal-1** [comment]
It was just a tensorflow version issue. Does not work with tensorflow2.
